### ISSUE TITLE
Java DISPLAY variable error when running tracer

### ISSUE THREAD

**Issue by tiagobrc** [Teichlab/tracer#115]
Can't determine the origin of this error. As far as I know, Tracer is not trying to use the display variable. 

Also didn't see this error anywhere I could search for. 

Does this mean anything I am missing ? What can I do to fix this ?

I am using a cluster system running slurm.  Tracer is installed within a conda environment.

Thanks for your attention,

Tiago

```
tracer test -p 1 -c tracer.conf 

Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:128)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.Toolkit$2.run(Toolkit.java:860)
        at java.awt.Toolkit$2.run(Toolkit.java:855)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1302)
        at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
        at tracer.application.TracerApp.main(Unknown Source)
```

**Comment by tiagobrc** [comment]
This behavior was solved by using:

```
conda uninstall statsmodels --yes
conda install -c taugspurger statsmodels=0.8.0     
```
