### ISSUE TITLE
AssertionError during tracer installation

### ISSUE THREAD

**Issue by svalkiers** [Teichlab/tracer#122]
Hi,

I followed the installation instructions as explained in the README, and edited the tracer.conf file accordingly. When I try to test the installation, I get an `AssertionError: Species not found in resources` error.

Code:
```
tracer test -p 1 -c tracer.conf
```

Terminal output:
```
Traceback (most recent call last):
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/bin/tracer", line 33, in <module>
    sys.exit(load_entry_point('tracer==0.5', 'console_scripts', 'tracer')())
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/tasks.py", line 1217, in run
    Assembler(resource_dir=self.resource_dir, ncores=str(self.ncores),
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/tasks.py", line 324, in __init__
    self.species_root = self.get_species_root(self.species,
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/tasks.py", line 209, in get_species_root
    assert os.path.isdir(resources_root), "Species not found in resources"
AssertionError: Species not found in resources
```

Please find the contents of the tracer.conf file here:
```
#Configuration file for TraCeR#

[tool_locations]
#paths to tools used by TraCeR for alignment, quantitation, etc
#bowtie2_path = /path/to/bowtie2
#bowtie2-build_path = /path/to/bowtie2-build
#igblastn_path = /home/sebastiaan/phd/tools/igblast/bin/igblastn
#makeblastdb_path = /path/to/makeblastdb
#kallisto_path = /path/to/kallisto
#salmon_path = /path/to/salmon
#trinity_path = /path/to/trinity
#dot_path = /path/to/dot
#neato_path = /path/to/neato


[trinity_options]
#line below specifies maximum memory for Trinity Jellyfish component. Set it appropriately for your environment.
max_jellyfish_memory = 1G

#uncomment the line below if you've got a configuration file for Trinity to use a computing grid 
#trinity_grid_conf = /path/to/trinity/grid.conf

#uncomment the line below to explicitly specify Trinity version. Options are '1' or '2'
#trinity_version = 2

#### <---- beginning of trinity specialized options
# additional Trinity options in case you're dealing with very short reads (say 25 base reads)
# and want to achieve high sensitivity with questionable specificity, in other words
# trying to extract whatever you can from the data you have:

###  note, default Trinity kmer length is 25
#trinity_kmer_length = 17

### below stops trinity at the initial inchworm (greedy kmer extension) step.
#inchworm_only = True

#### end of trinity specialized options ---->


[IgBlast_options]
igblast_seqtype = TCR

[base_transcriptomes]
# reference transcriptomes for kallisto/salmon.  Just point to the raw transcriptome fasta files.
Mmus = /home/sebastiaan/phd/tools/salmon/mouse/Mus_musculus_GRCm39_E110_cdna_ERCC.fasta
Hsap = /home/sebastiaan/phd/tools/salmon/human/Homo_sapiens_GRCh38.p14_E110_cdna_ERCC.fasta

[salmon_base_indices]
# salmon indices created from [base_transcriptomes] above; needed only when option --small_index is used
Mmus = /home/sebastiaan/phd/tools/salmon/mouse/Mus_musculus_GRCm39_E110_cdna_ERCC
Hsap = /home/sebastiaan/phd/tools/salmon/human/Homo_sapiens_GRCh38.p14_E110_cdna_ERCC

[kallisto_base_indices]
# kallisto indices created from [base_transcriptomes] above; needed only when option --small_index is used
Mmus = /path/to/kallisto/index_for_Mmus
Hsap = /path/to/kallisto/index_for_Hsap

[salmon_options]
# line below specifies type of sequencing library for Salmon; if not specified, automatic detection (--libType A) is used 
#libType = A

# line below specifies minimum acceptable length for valid match in salmon's quasi mapping; if not specified, default value of 31 is used
#kmerLen = 31

[tracer_location]
#Path to direcetory where TraCeR was originally downloaded
tracer_path = /home/sebastiaan/phd/tools/tracer/tracer
```

Thank you.

**Comment by lsy5011** [comment]
Hi! I'm currently facing the same issue.
May i know how you solve it? cause i did customized the conf file to the correct path but yet can't solve it.
Thanks!

**Comment by lsy5011** [comment]
Thanks alot! 
By the way did you meeet this issues when you running test?
![image](https://github.com/Teichlab/tracer/assets/45956944/28f672d1-0175-4c61-a73f-4e23512af56d)

**Comment by svalkiers** [comment]
Hmm no I did not. The error does not look very informative. Did you prepare the reference transcriptomes as instructed in https://www.nxn.se/valent/2016/10/3/the-first-steps-in-rna-seq-expression-analysis-single-cell-and-other ?

**Comment by lsy5011** [comment]
> Hmm no I did not. The error does not look very informative. Did you prepare the reference transcriptomes as instructed in https://www.nxn.se/valent/2016/10/3/the-first-steps-in-rna-seq-expression-analysis-single-cell-and-other ?

Yes i did! but the attributes part seems like changed a lil bit. My options like following:
![image](https://github.com/Teichlab/tracer/assets/45956944/e5f68c2c-a24f-4a42-bbd5-7bc7c31621ad)
Is it the same with you? because i didn't saw any similar issues posted here.
But i didn't do the genemap part, i just finish the references and indexing part. I guess it's fine right?

**Comment by lsy5011** [comment]
![image](https://github.com/Teichlab/tracer/assets/45956944/a7e3d72b-14b6-4924-bddd-aa04b993ad89)
and also is this part refer to the directory? cause in my case after indexing the output is a directory.
