### ISSUE TITLE
tracer summarise fails with uninformative error

### ISSUE THREAD

**Issue by svalkiers** [Teichlab/tracer#123]
Hi,

When running the `tracer summarise` function, I get the following error:
```
Traceback (most recent call last):
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/bin/tracer", line 33, in <module>
    sys.exit(load_entry_point('tracer==0.5', 'console_scripts', 'tracer')())
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/tasks.py", line 712, in run
    dot = self.get_binary('dot')
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/tasks.py", line 69, in get_binary
    return check_binary(name, user_path)
  File "/home/sebastiaan/miniconda3/envs/tcr_epi_benchmark/lib/python3.8/site-packages/tracer-0.5-py3.8.egg/tracerlib/io.py", line 154, in check_binary
    raise OSError(
OSError: Required binary not found: dot. Please add to PATH or specify location in config file.
256
```
It is unclear to me what 256 means in this case? Any idea where I need to make adjustments in the config file?

**Comment by NickEngland** [comment]
Have you installed all the dependencies, or are you running from Docker?

256 is the error code for the OS saying it couldn't find the binary it was asked to run. So here Python is telling the OS to run dot, which it can't find so it is causing the 256 error code.

Do you have dot installed?
