### ISSUE TITLE
igblast error

### ISSUE THREAD

**Issue by baj12** [Teichlab/tracer#38]
Hi,

I am trying to tracer using the sample data using the following command line:

 tracer assemble -p 8 -c tracer.conf cell1_1.fastq cell1_2.fastq  cellname bjtest

I am getting the following error message:

###################################################################
Butterfly assemblies are written to /pasteur/entites/Cih/bernd/indices/tracer/test_data/bjtest/cellname/Trinity_output/Trinity_cellname_TCR_B.Trinity.fasta
###################################################################

##Running IgBLAST##
Performing IgBlast on ['TCR_A', 'TCR_B']
##TCR_A##
##TCR_B##

Traceback (most recent call last):
  File "/mount/gensoft2/exe/tracer/0.5.0/bin/tracer", line 9, in <module>
    load_entry_point('tracer==0.5', 'console_scripts', 'tracer')()
  File "/mount/gensoft2/exe/tracer/0.5.0/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/mount/gensoft2/exe/tracer/0.5.0/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py", line 323, in run
    cell = self.ig_blast()
  File "/mount/gensoft2/exe/tracer/0.5.0/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py", line 452, in ig_blast
    self.max_junc_len)
  File "/mount/gensoft2/exe/tracer/0.5.0/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/io.py", line 113, in parse_IgBLAST
    loci, max_junc_len)
  File "/mount/gensoft2/exe/tracer/0.5.0/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tracer_func.py", line 114, in find_possible_alignments
    locus)
  File "/mount/gensoft2/exe/tracer/0.5.0/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tracer_func.py", line 282, in process_hit_table
    segment = entry[2]
IndexError: list index out of range

using the following program versions:
bash-4.1$ module list
Currently Loaded Modulefiles:
  1) bowtie/1.1.1          3) java/1.7.0            5) salmon/0.7.2          7) graphviz/2.38.0       9) tracer/0.5.0
  2) samtools/0.1.19       4) trinityrnaseq/2.0.6   6) kallisto/0.43.1       8) bowtie2/2.1.0        10) igblast/1.7.0

Would you have any idea how I can further investigate this problem?

Thx,

Bernd

**Comment by mstubb** [comment]
Hi Bernd,

Are you using the latest version of TraCeR from the `master` branch? 

If not, please update and try again.

If you are or if the problem continues, please can you zip and send me the contents of `/pasteur/entites/Cih/bernd/indices/tracer/test_data/bjtest/cellname/`. 

Thanks!

Mike

**Comment by mstubb** [comment]
This is related to Issues #15 #16 and #22. I've now generalised the fix further so that it should now work for all newer IgBLAST versions.
