### ISSUE TITLE
igblast setup

### ISSUE THREAD

**Issue by oeco28** [Teichlab/tracer#48]
Hello, 
 I seem to be having an issue with the IGblast setup. all the executables are in the path, and I have already placed the database for humans in the executable bin for igblastn, but I am getting an error in the test set that reads as follow:

##Running IgBLAST##
Traceback (most recent call last):
  File "./tracer", line 21, in <module>
    launch()
  File "/home/repository_software/tracer-master/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/home/repository_software/tracer-master/tracerlib/tasks.py", line 1151, in run
    loci=['A', 'B'], max_junc_len=50).run()
  File "/home/repository_software/tracer-master/tracerlib/tasks.py", line 346, in run
    cell = self.ig_blast()
  File "/home/repository_software/tracer-master/tracerlib/tasks.py", line 460, in ig_blast
    self.resume_with_existing_files, fmt)
  File "/home/repository_software/tracer-master/tracerlib/tracer_func.py", line 1212, in run_IgBlast
    subprocess.check_call(command, stdout=out, stderr=DEVNULL)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/home/repository_software/ncbi-igblast-1.7.0/bin/igblastn', '-germline_db_V', '/home/repository_software/tracer-master/resources/Mmus/igblast_dbs/TCR_V.fa', '-germline_db_D', '/home/repository_software/tracer-master/resources/Mmus/igblast_dbs/TCR_D.fa', '-germline_db_J', '/home/repository_software/tracer-master/resources/Mmus/igblast_dbs/TCR_J.fa', '-domain_system', 'imgt', '-organism', 'mouse', '-ig_seqtype', u'TCR', '-show_translation', '-num_alignments_V', '5', '-num_alignments_D', '5', '-num_alignments_J', '5', '-outfmt', '3', '-query', '/home/repository_software/tracer-master/testout/results/cell1/Trinity_output/cell1_TCR_A.Trinity.fasta']' returned non-zero exit status 1

Is this an issue you have come across?

thank you,
Omar

**Comment by mstubb** [comment]
Hi Omar,

Please check to see if you have done the following:

1. Download the separate internal_data directory from ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/internal_data and put it into the same directory as the IgBlast executable.

2. Set the $IGDATA environment variable to point to the location of the IgBlast executable. So, in your case you want to run the following at the command line:

`export IGDATA=/home/repository_software/ncbi-igblast-1.7.0/bin`


Please let me know if this works. If not, I'll be happy to help further.

Best,

Mike

**Comment by oeco28** [comment]
Hi Mike,
  I have done that. This is the structure of the folders:
    I dowloaded the human and mouse data and it is in:
/home/repository_software/ncbi-igblast-1.7.0/bin/human/igblast_dbs/
/home/repository_software/ncbi-igblast-1.7.0/bin/mouse/igblast_dbs/

echo $IGDATA shows:
/home/repository_software/ncbi-igblast-1.7.0/bin

and the content of folder for each organism is the full set of mouse_TR_V.(nhr, nin, nog, nsd, nsi, nsq, phr, pin, pog, psd, psi, psq) files. 

I also thought that the problem was not giving the full path to the IGDATA, so I changed it to the full path:
/home/repository_software/ncbi-igblast-1.7.0/bin/mouse/igblast_dbs/

but it still produces the same error.

**Comment by mstubb** [comment]
Hi Omar,

You should have a path as follows:

`/home/repository_software/ncbi-igblast-1.7.0/bin/internal_data` where the `internal_data` directory came from: ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/internal_data. Do you have that? 

If not, please download that directory from the NIH FTP site and see if you can then run Tracer. It expects that directory to be there.

I have also just pushed a change to the Github repo that gives much more informative error messages if IgBlast fails. If the above doesn't work, please download the lastest version from the Master branch and let me know what error message you get. 

Thanks!

Mike

**Comment by mstubb** [comment]
Hi @oeco28,

Were you able to resolve this? I'll close this issue if it's now working for you. 

If not, let me know, and I'll be happy to help.

Best,

Mike

**Comment by dustyl259** [comment]
I have a similar issue. I am running igblast on Windows and am observing error: "BLAST query/options error: Germline annotation database C:\Program Files\ncbi-igblast-1.9.0\bin\internal_data\human\human_TR_V could not be found in [internal_data] directory"

I set environment variable IGDATA to the "bin" directory where the igblast executable is and am seeing the error above. There does not seem to be a clear answer to this in any online forum involving IgBlast. Please help.

**Comment by aeolianine** [comment]
I have the same problem on Linux. 
I set IGDATA='/tools/ncbi-igblast-1.14.0/internal_data/', and whether I use it directly (-b pathString), or via the variable $IGDATA (-b $IGDATA), or with different super/sub-path versions, I get the exact same error message:

**BLAST query/options error: Germline annotation database human/human_V could not be found in [internal_data] directory**

The folder "internal_data/" does contain a "human" folder with "human_V*' files in it.
