### ISSUE TITLE
tracer breaks down after kallisto

### ISSUE THREAD

**Issue by tiagobrc** [Teichlab/tracer#59]
I could not verify the reason for this error. This is the test run of tracer. Just after kallisto, this strange error popped.

```
##Quantifying with Kallisto##

[quant] fragment length distribution will be estimated from the data
[index] k-mer length: 31
[index] number of targets: 63,852
[index] number of k-mers: 72,966,044
[index] number of equivalence classes: 194,076
[quant] running in paired-end mode
[quant] will process pair 1: /home/tiago/programs/tracer/test_data/cell1_1.fastq
                             /home/tiago/programs/tracer/test_data/cell1_2.fastq
[quant] finding pseudoalignments for the reads ... done
[quant] processed 1,135 reads, 1,044 reads pseudoaligned
[quant] estimated average fragment length: 148.91
[   em] quantifying the abundances ... done
[   em] the Expectation-Maximization algorithm ran for 52 rounds


##Filtering by read count##
Traceback (most recent call last):
  File "/home/tiago/bin/tracer", line 21, in <module>
    launch()
  File "/home/tiago/programs/tracer/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/home/tiago/programs/tracer/tracerlib/tasks.py", line 1207, in run
    loci=['A', 'B'], species='Mmus').run()
  File "/home/tiago/programs/tracer/tracerlib/tasks.py", line 1055, in run
    network_colours)
  File "/home/tiago/programs/tracer/tracerlib/tracer_func.py", line 787, in draw_network_from_cells
    cells, False, "box", dot, neato, receptor, loci, network_colours)
  File "/home/tiago/programs/tracer/tracerlib/tracer_func.py", line 743, in make_cell_network_from_dna
    to_remove = [n for n in deg if deg[n] == 0]
  File "/home/tiago/programs/tracer/tracerlib/tracer_func.py", line 743, in <listcomp>
    to_remove = [n for n in deg if deg[n] == 0]
  File "/home/tiago/anaconda3/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 502, in __getitem__
    nbrs = self._succ[n]
KeyError: (<tracerlib.core.Cell object at 0x7f955250c470>, 0)


```

Do you have any thoughts about this?

**Comment by idalind** [comment]
Hi,
Exactly which command did you run, and what was your memory limit?

**Comment by mstubb** [comment]
Hi @tiagobrc, have you managed to resolve this? 

We're happy to help if you can let us know some more details.

Thanks!

Mike

**Comment by cramirezs** [comment]
Hello,

I have what I think is the same error. It appears after running the summarise step. Could you help me with this?

`tracer summarise results/ -s Hsap --config /mnt/BioHome/ciro/bin/tracer-master/tracer.conf -i`

The full error is:

```
/mnt/BioHome/ciro/bin/miniconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
/mnt/BioHome/ciro/bin/miniconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
Traceback (most recent call last):
  File "/mnt/BioHome/ciro/bin/tracer-master/tracer", line 21, in <module>
    launch()
  File "/mnt/BioHome/ciro/bin/tracer-master/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/mnt/BioHome/ciro/bin/tracer-master/tracerlib/tasks.py", line 1009, in run
    network_colours)
  File "/mnt/BioHome/ciro/bin/tracer-master/tracerlib/tracer_func.py", line 783, in draw_network_from_cells
    cells, False, "box", dot, neato, receptor, loci, network_colours)
  File "/mnt/BioHome/ciro/bin/tracer-master/tracerlib/tracer_func.py", line 739, in make_cell_network_from_dna
    to_remove = [n for n in deg if deg[n] == 0]
  File "/mnt/BioHome/ciro/bin/tracer-master/tracerlib/tracer_func.py", line 739, in <listcomp>
    to_remove = [n for n in deg if deg[n] == 0]
  File "/mnt/BioHome/ciro/bin/miniconda3/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 507, in __getitem__
    nbrs = self._succ[n]
KeyError: (<tracerlib.core.Cell object at 0x7f917a5af160>, 4)
```

Thank you very much,
Ciro

**Comment by tiagobrc** [comment]
> Hi @tiagobrc, have you managed to resolve this?
> 
> We're happy to help if you can let us know some more details.
> 
> Thanks!
> 
> Mike

Hi! I am so sorry for the late follow-up. I will be testing this again soon and report here.

**Comment by lchong** [comment]
I'm having the same issue when running the test from within the tracer directory (`./tracer test --config_file tracer.conf`).

At the stage of filtering by read counts:

```
##Filtering by read count##
/projects/clc/usr/anaconda/5.1.0/lib/python3.6/site-packages/matplotlib/axes/_axes.py:6462: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
  warnings.warn("The 'normed' kwarg is deprecated, and has been "
Traceback (most recent call last):
  File "./tracer", line 21, in <module>
    launch()
  File "/projects/clc/usr/tracer/tracer-0.6.0/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/projects/clc/usr/tracer/tracer-0.6.0/tracerlib/tasks.py", line 1212, in run
    loci=['A', 'B'], species='Mmus').run()
  File "/projects/clc/usr/tracer/tracer-0.6.0/tracerlib/tasks.py", line 1060, in run
    network_colours)
  File "/projects/clc/usr/tracer/tracer-0.6.0/tracerlib/tracer_func.py", line 797, in draw_network_from_cells
    cells, False, "box", dot, neato, receptor, loci, network_colours)
  File "/projects/clc/usr/tracer/tracer-0.6.0/tracerlib/tracer_func.py", line 753, in make_cell_network_from_dna
    to_remove = [n for n in deg if deg[n] == 0]
  File "/projects/clc/usr/tracer/tracer-0.6.0/tracerlib/tracer_func.py", line 753, in <listcomp>
    to_remove = [n for n in deg if deg[n] == 0]
  File "/projects/clc/usr/anaconda/5.1.0/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 507, in __getitem__
    nbrs = self._succ[n]
KeyError: (<tracerlib.core.Cell object at 0x7f41b1a09a58>, 2)
```

My config file specifies the location of the tools (all installed with anaconda) and the references, I haven't altered anything else. I'm running the test on centos6. Let me know what other details I can provide.

**Comment by lchong** [comment]
Hi Mike,

That seems to have done the trick, I'm able to generate the test data results now.

Thank you!

**Comment by mstubb** [comment]
Great!
