### ISSUE TITLE
Running docker image with test data fails.

### ISSUE THREAD

**Issue by gitbuckley** [Teichlab/tracer#66]
Running this command in tracer/ as per the README:
docker run -it --rm -v $PWD:/scratch -w /scratch teichlab/tracer test -o test_data

Results in this error:

[build] counting k-mers ... Traceback (most recent call last):
  File "/usr/local/bin/tracer", line 11, in <module>
    load_entry_point('tracer==0.5', 'console_scripts', 'tracer')()
  File "/usr/local/lib/python3.5/dist-packages/tracer-0.5-py3.5.egg/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/lib/python3.5/dist-packages/tracer-0.5-py3.5.egg/tracerlib/tasks.py", line 1206, in run
    loci=['A', 'B'], max_junc_len=50).run()
  File "/usr/local/lib/python3.5/dist-packages/tracer-0.5-py3.5.egg/tracerlib/tasks.py", line 372, in run
    self.quantify(cell)
  File "/usr/local/lib/python3.5/dist-packages/tracer-0.5-py3.5.egg/tracerlib/tasks.py", line 626, in quantify
    self.fragment_length, self.fragment_sd)
  File "/usr/local/lib/python3.5/dist-packages/tracer-0.5-py3.5.egg/tracerlib/tracer_func.py", line 1309, in quantify_with_kallisto
    subprocess.check_call(index_command)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/kallisto_linux-v0.43.1/kallisto', 'index', '-i', '/scratch/test_data/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.idx', '/scratch/test_data/results/cell1/expression_quantification/kallisto_index/cell1_transcriptome.fa']' returned non-zero exit status -9

Any suggestions?

**Comment by gitbuckley** [comment]
Resolved by increasing memory available to docker.

**Comment by liyongzheng1** [comment]
> Resolved by increasing memory available to docker.

I met a similar error, could you tell me how much memory you allocated?

**Comment by mstubb** [comment]
I’d try 6–8 Gb

Mike

**Comment by liyongzheng1** [comment]
> I’d try 6–8 Gb Mike
> […](#)
> On 28 Feb 2019, at 22:57, liyongzheng1 ***@***.***> wrote: Resolved by increasing memory available to docker. I met a similar error, could you tell me how much memory you allocated? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

OK, thanks for your response.
