### ISSUE TITLE
Running igblast returns an error

### ISSUE THREAD

**Issue by FredieD** [Teichlab/tracer#70]
Hi,
I'm going to testing TraCer by runing `tracer test`.But everytime it returns an error after printing runing IgBlast,fully copy as follows:
`##Running IgBLAST##
CMD failed:
 
Traceback (most recent call last):
  File "/share/apps/anaconda3/bin/tracer", line 9, in <module>
    load_entry_point('tracer==0.5', 'console_scripts', 'tracer')()
  File "/share/apps/anaconda3/lib/python3.5/site-packages/tracer-0.5-py3.5.egg/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/share/apps/anaconda3/lib/python3.5/site-packages/tracer-0.5-py3.5.egg/tracerlib/tasks.py", line 1206, in run
    loci=['A', 'B'], max_junc_len=50).run()
  File "/share/apps/anaconda3/lib/python3.5/site-packages/tracer-0.5-py3.5.egg/tracerlib/tasks.py", line 371, in run
    cell = self.ig_blast()
  File "/share/apps/anaconda3/lib/python3.5/site-packages/tracer-0.5-py3.5.egg/tracerlib/tasks.py", line 502, in ig_blast
    self.resume_with_existing_files, fmt)
  File "/share/apps/anaconda3/lib/python3.5/site-packages/tracer-0.5-py3.5.egg/tracerlib/tracer_func.py", line 1265, in run_IgBlast
    print(" ").join(pipes.quote(s) for s in command)
AttributeError: 'NoneType' object has no attribute 'join'
`
I followed the installation to install igblast,the tree of `igblast/bin` is as follows:
`|-- igblastn
|-- igblastp
|-- internal_data
|   `-- human
|       |-- human.ndm.imgt
|       |-- human.ndm.kabat
|       |-- human.pdm.imgt
|       |-- human.pdm.kabat
|       |-- human_TR_V.nhr
|       |-- human_TR_V.nin
|       |-- human_TR_V.nog
|       |-- human_TR_V.nsd
|       |-- human_TR_V.nsi
|       |-- human_TR_V.nsq
|       |-- human_TR_V.phr
|       |-- human_TR_V.pin
|       |-- human_TR_V.pog
|       |-- human_TR_V.psd
|       |-- human_TR_V.psi
|       |-- human_TR_V.psq
|       |-- human_V.nhr
|       |-- human_V.nin
|       |-- human_V.nog
|       |-- human_V.nsd
|       |-- human_V.nsi
|       |-- human_V.nsq
|       |-- human_V.phr
|       |-- human_V.pin
|       |-- human_V.pog
|       |-- human_V.psd
|       |-- human_V.psi
|       `-- human_V.psq
`-- makeblastdb
`
And I set $IGDATA to ~/tool/igblast-1.9.0/bin

I got a file under test_data/results/cell1/IgBLAST_output/ named cell1_TCR_A_fmt3.IgBLASTOut,but it's empty,so I tried to run igblast with cell1_TCR_A.Trinity.fasta under test_data/results/cell1/Trinity_output/ by `igblastn -germline_db_V /home/user/tool/tracer-master/resources/Hsap/igblast_dbs/TCR_V.fa \
         -germline_db_D /home/user/tool/tracer-master/resources/Hsap/igblast_dbs/TCR_D.fa \
         -germline_db_J /home/user/tool/tracer-master/resources/Hsap/igblast_dbs/TCR_J.fa \
         -domain_system imgt \
         -organism human \
         -ig_seqtype TCR \
         -num_alignments_V 5 \
         -num_alignments_D 5 \
         -num_alignments_J 5 \
         -outfmt 3 \
         -query cell1_TCR_A.Trinity.fasta `
It looks like everything is fine,but there is a warning message above:`Warning: Auxilary data file could not be found`.
I don't know which step is going to be a problem.

**Comment by mstubb** [comment]
Hi, 

Thanks for this. 

This specific crash is happening because of a bug in the way that TraCeR tries to report an error if IgBlast fails. I've just pushed a fix for this to the `master` branch. Please can you update to the latest commit to and then try running `tracer test` again - you should now get more informative output that will report the IgBLAST error. Let me know what that is and I'll see if I can help.

Very best,

Mike

**Comment by SeadonXing** [comment]
##Running IgBLAST##
CMD failed:
 
Traceback (most recent call last):
  File "/Bailab5/xingxudong/Software/anaconda2/bin/tracer", line 11, in <module>
    load_entry_point('tracer==0.5', 'console_scripts', 'tracer')()
  File "/home/xingxudong/.local/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/home/xingxudong/.local/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py", line 1206, in run
    loci=['A', 'B'], max_junc_len=50).run()
  File "/home/xingxudong/.local/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py", line 371, in run
    cell = self.ig_blast()
  File "/home/xingxudong/.local/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py", line 502, in ig_blast
    self.resume_with_existing_files, fmt)
  File "/home/xingxudong/.local/lib/python2.7/site-packages/tracer-0.5-py2.7.egg/tracerlib/tracer_func.py", line 1265, in run_IgBlast
    print(" ").join(pipes.quote(s) for s in command)
AttributeError: 'NoneType' object has no attribute 'join'

I got the same errors by using tracer-0.6.0. Have you fixed the bug ? How to solve this problems ?

Best 
Xudong

**Comment by SeadonXing** [comment]
##Running IgBLAST##
CMD failed:
/Bailab5/xingxudong/Software/ncbi-igblast-1.10.0/bin/igblastn -germline_db_V /Bailab5/xingxudong/Software/tracer-master/resources/Mmus/igblast_dbs/TCR_V.fa -germline_db_D /Bailab5/xingxudong/Software/tracer-master/resources/Mmus/igblast_dbs/TCR_D.fa -germline_db_J /Bailab5/xingxudong/Software/tracer-master/resources/Mmus/igblast_dbs/TCR_J.fa -domain_system imgt -organism mouse -ig_seqtype TCR -show_translation -num_alignments_V 5 -num_alignments_D 5 -num_alignments_J 5 -outfmt 3 -auxiliary_data optional_file/mouse_gl.aux -query /Bailab5/xingxudong/Test/TraCeR/results/cell1/Trinity_output/cell1_TCR_A.Trinity.fasta

BLAST query/options error: Germline annotation database mouse/mouse_TR_V could not be found in [internal_data] directory
Please refer to the BLAST+ user manual.

When I update to the latest commit to and then try running tracer test again - I got the IgBLAST error

**Comment by mstubb** [comment]
Have you got a working version of IgBlast as per the instructions here? https://github.com/Teichlab/tracer/blob/master/README.md#installing-igblast

Make sure you've downloaded the `internal_data` directory to the correct place and set your `$IGDATA` environment variable.

**Comment by SeadonXing** [comment]
Cheers , I solve the problems by  run  "export IGDATA=/Bailab5/xingxudong/Software/ncbi-igblast-1.10.0/bin"  straightly.
But I still confused that I add the IGDATA path by  vim  and source /home/.bash_profile file.
command is : 
IGDATA=/Bailab5/xingxudong/Software/ncbi-igblast-1.10.0/bin:$IGDATA

But somehow It cant be found by the systems.
Anyway, thanks borther !

Best
Xudong
