### ISSUE TITLE
tracer 0.6 test fails in summarise stage:

### ISSUE THREAD

**Issue by hkoohy** [Teichlab/tracer#84]
Hi Mike, 
I have installed tracer 0.6 in an virenv and have been trying to get it run. But the test function fails at summarise stage.
The following is the error that i didnt find it very informative. I have additionally tested with a few in-house cells, it again fails at the summarise stage. In the filtered_TCRAB_summary directory, I see recombinants.txt, reconstructed lengths (both pdf and txt) and TCR_summary files but nothing more whereas I was expecting to see some information about clones and clonotypes.
The command I have been using is ::
python tracer test -p 2 -c $HOME/tracer_v6/tracer-0.6.0/tracer.conf --no_networks
or 
python tracer summarise ${out_dir} -c $HOME/tracer_v6/tracer-0.6.0/tracer.conf -s Hsap --no_networks 

I appreciate if you could please point us what we do wrong.
##### here is the error I get:
##Filtering by read count##
Traceback (most recent call last):
  File "tracer", line 21, in <module>
    launch()
  File "/t1-home/molimm2/haskoohy/tracer_v6/tracer-0.6.0/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/t1-home/molimm2/haskoohy/tracer_v6/tracer-0.6.0/tracerlib/tasks.py", line 1212, in run
    loci=['A', 'B'], species='Mmus').run()
  File "/t1-home/molimm2/haskoohy/tracer_v6/tracer-0.6.0/tracerlib/tasks.py", line 1060, in run
    network_colours)
  File "/t1-home/molimm2/haskoohy/tracer_v6/tracer-0.6.0/tracerlib/tracer_func.py", line 797, in draw_network_from_cells
    cells, False, "box", dot, neato, receptor, loci, network_colours)
  File "/t1-home/molimm2/haskoohy/tracer_v6/tracer-0.6.0/tracerlib/tracer_func.py", line 753, in make_cell_network_from_dna
    to_remove = [n for n in deg if deg[n] == 0]
  File "/t1-home/molimm2/haskoohy/tracer_v6/tracer-0.6.0/tracerlib/tracer_func.py", line 753, in <listcomp>
    to_remove = [n for n in deg if deg[n] == 0]
  File "/t1-home/molimm2/haskoohy/tracer_env/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 507, in __getitem__
    nbrs = self._succ[n]
KeyError: (<tracerlib.core.Cell object at 0x7f4250c73c88>, 2)

**Comment by mstubb** [comment]
Hi Hashem,

What version of Networkx do you have installed? Tracer doesn't work with v2 so you'll need v1.11 and I *think* that's what's causing this problem.

Probably also best to download the latest version from the Master branch than use v0.6 just in case that helps.

Let me know if that doesn't fix it.

Cheers,

Mike

**Comment by hkoohy** [comment]
Hi Mike,
I can confirm that the problem is solved in case you want to close this issue. Once again thank you so much for your quick support.

**Comment by mstubb** [comment]
Great! Glad it's working.
