### ISSUE TITLE
Running "tracer test -p 1 -c tracer.config" problem with dot

### ISSUE THREAD

**Issue by solyris** [Teichlab/tracer#86]
Hi, 

I am testing the tracer run on the test data and hit the error below which is just after the quantifying by kallisto stage. It seems like my version of dot is not supporting "-T pdf" in particular, may I know which version of Graphviz is supporting that? Or what option can I use to by-pass this without damage to the downstream analysis?

Regards
Solyris

##Filtering by read count##
Format: "pdf" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pic plain plain-ext pov ps ps2 svg svgz tk vml vmlz xdot xdot1.2 xdot1.4 xdot_json
Traceback (most recent call last):
  File "/usr/local/bin/tracer", line 11, in <module>
    load_entry_point('tracer==0.5', 'console_scripts', 'tracer')()
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.5-py2.7.egg/tracerlib/launcher.py", line 43, in launch
    Task().run()
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py", line 1230, in run
    loci=['A', 'B'], species='Mmus').run()
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.5-py2.7.egg/tracerlib/tasks.py", line 1078, in run
    network_colours)
  File "/usr/local/lib/python2.7/dist-packages/tracer-0.5-py2.7.egg/tracerlib/tracer_func.py", line 831, in draw_network_from_cells
    subprocess.check_call(command)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/dot', '-Gsplines=true', '-Goverlap=false', '-Gsep=0.4', '-o', '/home/ubuntu/software/tracer-master/test_data/results/filtered_TCRAB_summary/clonotype_network_with_identifiers.pdf', '-T', 'pdf', '/home/ubuntu/software/tracer-master/test_data/results/filtered_TCRAB_summary/clonotype_network_with_identifiers.dot']' returned non-zero exit status 1

**Comment by mstubb** [comment]
Hi,

Sorry, I don't know which specific graphviz versions support PDF. 

You can use `tracer test -g svg` to get svg output or use any of the other options from the list in the error message. Or use `tracer test --no_networks` to stop it attempting to draw networks. 

Best,

Mike
